### ISSUE TITLE
rhostsrsaauthentication and rsaauthentication do not exist in OpenSSH >= 7.6

### ISSUE THREAD

**Issue by aft2d** [arillso/ansible.sshd#10]
The both options RhostsRSAAuthentication and RSAAuthentication from ssh_config got removed in OpenSSH 7.6.
Everytime I try to use the ssh config (on ubuntu 18.04 in my case) I get:
/etc/ssh/ssh_config line 72: Unsupported option "rhostsrsaauthentication"
/etc/ssh/ssh_config line 75: Unsupported option "rsaauthentication"

Unfortunately I couldn't verify that in a release note or changelog of OpenSSH, so I compared the man pages from the packages and noted that both options were removed in 7.6
Ubuntu 18.04 and Debian 10 use OpenSSH 7.6

**Comment by sbaerlocher** [comment]
In version 2.0.0 the problem is solved.
