### ISSUE TITLE
Missing var `sshd_config_path` for RedHat-8

### ISSUE THREAD

**Issue by FrankGiesecke** [arillso/ansible.sshd#29]
If the target system relies on RedHat 8, the role throws an error.

```
TASK [arillso.sshd : set hostkeys according to openssh-version] ****************
fatal: [****]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'sshd_config_path' is undefined\n\nThe error appears to be in '/builds/mw/infrastructure/ansible-management/projects/internal-server-landscape/.ansible/roles/arillso.sshd/tasks/distribution/subtasks/crypto.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set hostkeys according to openssh-version\n  ^ here\n"}
```

The reason for this is, that the file [vars/RedHat-8.yml](https://github.com/arillso/ansible.sshd/blob/master/vars/RedHat-8.yml) doesn't contain the definition of `sshd_config_path`.

The variable is also missing in:
* [vars/Oracle Linux-8.yml](https://github.com/arillso/ansible.sshd/blob/master/vars/Oracle%20Linux-8.yml)

Closes #22

**Comment by felixb** [comment]
Mind adding a `Rocky-8.yml` to support rocky linux with this PR?

**Comment by FrankGiesecke** [comment]
@felixb It might be better to create a single Issue for rocky linux support with all necessary information and fix this in a separate pull request.
Feel free to mention me in the issue and I will create a fix for this.

**Comment by felixb** [comment]
created a quick PR in #31

**Comment by FrankGiesecke** [comment]
So, let us hope that the PRs will be merged.
